### ISSUE TITLE
Jamulus API for external applications

### ISSUE THREAD

**Issue by thedrint** [Daninet/jamulus#1]
At the first, sorry my buggy english)

Is there some API for writers of external applications? It would be useful for creating more complex application, like juplin.org (this project was good alternative, but it is closed). I think that more social oriented application with Jamulus at base - would make WOW-effect.

But i understand. Goal of Jamulus - connect user's audiostreams through internet. No more. Other features would be secondaries. So, if some API would be integrated, it would be cool, other developers could realize projects based on Jamulus:)

**Comment by ann0see** [comment]
Hi @thedrint Currently this seems to be a quite common request. Maybe have a look at [the new repo](https://github.com/corrados/jamulus)
